# Generated by Django 5.0.7 on 2024-07-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_actor_bio_movie_description_movie_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="director",
            name="bio",
            field=models.TextField(default="asd"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="actor",
            name="bio",
            field=models.TextField(default="asd"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(default="weq"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(default="asdq", max_length=255),
            preserve_default=False,
        ),
    ]
