# Generated by Django 5.0.7 on 2024-07-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0004_alter_actor_bio_alter_director_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="movie.actor"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="director",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="movie.director"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="movie.genre"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="favourite_films",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="movie.movie"
            ),
        ),
    ]
