# Generated by Django 5.0.7 on 2024-07-17 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0005_alter_movie_actors_alter_movie_director_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="favourite_films",
            new_name="favourite_movies",
        ),
    ]
