# Generated by Django 5.0.7 on 2024-07-18 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0006_rename_favourite_films_user_favourite_movies"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="rating",
        ),
    ]
