# Generated by Django 5.0.7 on 2024-07-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0007_remove_movie_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="user_profile_pics/"
            ),
        ),
    ]
