# Generated by Django 5.0.7 on 2024-07-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0008_user_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                blank=True, default="blank.png", null=True, upload_to=""
            ),
        ),
    ]
