# Generated by Django 5.0.7 on 2024-07-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0010_alter_user_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="poster",
            field=models.ImageField(
                blank=True, default="blank_poster.png", upload_to=""
            ),
        ),
    ]
