# Generated by Django 5.0.7 on 2024-07-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0011_movie_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="photo",
            field=models.ImageField(
                blank=True, default="blank_people.jpg", upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.ImageField(
                blank=True, default="blank_poster.webp", upload_to=""
            ),
        ),
    ]
