# Generated by Django 5.0.7 on 2024-07-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0012_actor_photo_alter_movie_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="director",
            name="photo",
            field=models.ImageField(
                blank=True, default="blank_people.jpg", upload_to=""
            ),
        ),
    ]
