# Generated by Django 5.0.7 on 2024-07-19 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0013_director_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="film",
            new_name="movie",
        ),
    ]
