# Generated by Django 5.0.7 on 2024-07-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0014_rename_film_review_movie"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="director",
            new_name="directors",
        ),
    ]
