# Generated by Django 5.0.7 on 2024-07-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0015_rename_director_movie_directors"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="birth_year",
            field=models.DateField(default="2004-05-12"),
        ),
        migrations.AddField(
            model_name="director",
            name="birth_year",
            field=models.DateField(default="1994-07-19"),
        ),
    ]
