# Generated by Django 5.0.7 on 2024-07-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0016_actor_birth_year_director_birth_year"),
    ]

    operations = [
        migrations.RenameField(
            model_name="actor",
            old_name="birth_year",
            new_name="birth_date",
        ),
        migrations.RenameField(
            model_name="director",
            old_name="birth_year",
            new_name="birth_date",
        ),
    ]
