# Generated by Django 5.0.7 on 2024-07-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0017_rename_birth_year_actor_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actor",
            options={"ordering": ("first_name",)},
        ),
        migrations.AlterModelOptions(
            name="director",
            options={"ordering": ("first_name",)},
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ("title",)},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ("created_at",)},
        ),
    ]
