# Generated by Django 5.0.7 on 2024-07-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0018_alter_actor_options_alter_director_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ("-created_at",)},
        ),
    ]
