# Generated by Django 5.0.7 on 2024-07-21 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0019_alter_review_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="country",
            field=models.CharField(
                choices=[
                    ("US", "United States"),
                    ("CA", "Canada"),
                    ("FR", "France"),
                    ("DE", "Germany"),
                    ("UA", "Ukraine"),
                ],
                default="UA",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="duration",
            field=models.DurationField(default=datetime.timedelta(seconds=9000)),
        ),
        migrations.AddField(
            model_name="movie",
            name="release_date",
            field=models.DateField(blank=True, default="2004-05-12"),
        ),
    ]
