# Generated by Django 5.0.7 on 2024-07-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0020_movie_country_movie_duration_movie_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="birth_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="director",
            name="birth_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="country",
            field=models.CharField(
                choices=[
                    ("United States", "United States"),
                    ("Canada", "Canada"),
                    ("France", "France"),
                    ("Germany", "Germany"),
                    ("Ukraine", "Ukraine"),
                ],
                default="UA",
                max_length=63,
            ),
        ),
    ]
