# Generated by Django 5.0.7 on 2024-07-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0021_alter_actor_birth_date_alter_director_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="country",
            field=models.CharField(
                choices=[
                    ("United States", "United States"),
                    ("Canada", "Canada"),
                    ("France", "France"),
                    ("Germany", "Germany"),
                    ("Ukraine", "Ukraine"),
                ],
                default="Ukraine",
                max_length=63,
            ),
        ),
    ]
